### ISSUE TITLE
Phone numbers starting with 8,9 etc are not supported in address field of pagerduty User contact method resource 

### ISSUE THREAD

**Issue by pridumre** [PagerDuty/terraform-provider-pagerduty#591] opened 2022-11-24 14:07 UTC
Hello !

We were trying to create pagerduty_user_contact_method using terraform. We are using the terraform pagerduty provider version  2.6.4. Any phone numbers starting with 8, 9 etc in address field of user contact method resource is throwing below error as shown in image

**So the problems are like below:**
1. Address field in User contact method resource block is **only accepting numbers starting with 1 (1721234567).**
2. Its **not accepting  numbers starting with 8, 9**, 0 ( 8723450678 and 9876543241 etc ) in Pagerduty provider which is currently we are using as 2.6.4.
 

resource "pagerduty_user_contact_method" " contact" {
  user_id        = pagerduty_user.example.id
  type           = "phone_contact_method"
  **address      = "88999XXXXX"**
  label            = "Work"
  country_code = "+91"
}
![image](https://user-images.githubusercontent.com/116808475/203851976-14dc3b9d-e1b1-470e-9ba9-1138f1c8c94a.png)

![image](https://user-images.githubusercontent.com/116808475/203851562-fab82af0-aa17-44cb-86f2-f022e6987420.png)

**Terraform Version:
only working in provider 2.3.0 
All Versions affected > 2.3.0** 

Affected Resource(s)
pagerduty_user_contact_method using phone_contact_method or phone_contact_method

**Debug Output
Error: phone numbers should only contain digits**

Actual Behavior
Can't apply

References
I think the bug has been introduced here : https://github.com/PagerDuty/terraform-provider-pagerduty/pull/475/files

i think due to attached code mention in PR 475 which was merged in version 2.4.0 ,this issue is coming for all versions post that. Just to be sure we removed below code from user resource Go block **(pagerduty/resource_pagerduty_user_contact_method.go)** from latest provider 2.6.4 and generated custom provider which was working successfully ..Hence Requesting you to please check this. Any help of suggestions would be helpful

![image](https://user-images.githubusercontent.com/116808475/203800725-a68ef763-fd74-4742-9994-d83949ee0f3c.png)

**Comment by imjaroiswebdev** [comment] 2022-11-28 16:42
Hi @pridumre if I try to replicate your case using only my interpretation then I am not able to do it, and I'm also using Terraform Provider v2.6.4, however If I literally use your example even with the **XXXX** placeholder, then I get the error from the Provider, which is the expected behaviour since it only accepts numbers as the error message highlights.

## The result of my tests was the following...

### Mixing numbers with letters
![Screenshot 2022-11-28 at 13 24 48](https://user-images.githubusercontent.com/24704624/204331684-874daec5-9661-465a-8280-fcae92e85214.png)

### Entering only numbers
![Screenshot 2022-11-28 at 13 27 30](https://user-images.githubusercontent.com/24704624/204331781-4bcfba08-122d-40a4-8d9f-0ea764ae48cd.png)

Regarding the validation introduced with PR #475 that is also a desired and expected behaviour, because leading zeros should be dropped for phone numbers.

Finally, if after checking your configuration you still having the issue I would really appreciate if you could provide more details about you configuration, so I'll be able to help you further @pridumre.

**Comment by imjaroiswebdev** [comment] 2022-12-09 20:22
I'm proceeding to close this issue, but please if you still are experiencing this issue just reopen the issue commenting more details about what you are experiencing ✌🏽

**Closed by imjaroiswebdev** 2022-12-09 20:22 UTC
