### ISSUE TITLE
Support for Round Robin Scheduling

### ISSUE THREAD

**Issue by C6H6** [PagerDuty/terraform-provider-pagerduty#557] opened 2022-08-04 13:31 UTC
### Terraform Version
```
Terraform v1.2.6
on darwin_arm64
```

### Affected Resource(s)
- pagerduty_escalation_policy

### Expected Behavior
It looks like there is no support for "Round Robin Scheduling" in the provider even though it is possible to set this up using the API. This should be implemented. However, if there is a way to set this up that I missed, please comment with an explanation.

### Actual Behavior
No support for "Round Robin Scheduling"

### References
- https://support.pagerduty.com/docs/round-robin-scheduling

**Comment by aelmekeev** [comment] 2022-08-14 10:27
This a duplicate of https://github.com/PagerDuty/terraform-provider-pagerduty/issues/518

**Closed** 2024-09-25 17:32 UTC
