### ISSUE TITLE
500 Internal Server Error on pagerduty_response_play

### ISSUE THREAD

**Issue by li-adrienloiseau** [PagerDuty/terraform-provider-pagerduty#306] opened 2021-02-26 18:41 UTC
### Affected Resource(s): pagerduty_response_play

`
resource "pagerduty_response_play" "test" {
  name = "My Response Play"
  from = pagerduty_user.test_adrienloiseau.email

  responder {
    type = "escalation_policy_reference"
    id   = pagerduty_escalation_policy.test_ops.id
  }
  subscriber {
    type = "user_reference"
    id   = pagerduty_user.test_adrienloiseau.id
  }
  runnability = "services"
}`

### Error Output
`
pagerduty_response_play.test: Creating...
pagerduty_response_play.test: Still creating... [10s elapsed]
pagerduty_response_play.test: Still creating... [20s elapsed]
pagerduty_response_play.test: Still creating... [30s elapsed]
pagerduty_response_play.test: Still creating... [40s elapsed]
pagerduty_response_play.test: Still creating... [50s elapsed]
pagerduty_response_play.test: Still creating... [1m0s elapsed]
pagerduty_response_play.test: Still creating... [1m10s elapsed]
pagerduty_response_play.test: Still creating... [1m20s elapsed]
pagerduty_response_play.test: Still creating... [1m30s elapsed]
pagerduty_response_play.test: Still creating... [1m40s elapsed]
pagerduty_response_play.test: Still creating... [1m50s elapsed]
pagerduty_response_play.test: Still creating... [2m0s elapsed]

Error: POST API call to https://api.pagerduty.com/response_plays failed: 500 Internal Server Error

  on pagerduty_response_play.tf line 1, in resource "pagerduty_response_play" "test":
   1: resource "pagerduty_response_play" "test" {`

**Comment by christopherbox** [comment] 2021-03-02 21:31
Also confirming to be experiencing the same error

**Comment by stmcallister** [comment] 2021-03-11 01:31
🤔 I'm unable to reproduce. Would you be able to post the `TF_LOG` output surrounding the API request and response for this?

**Comment by christopherbox** [comment] 2021-03-12 20:09
Heres a quick trace output. I replaced the necessary stuff that I believe I need to hide.

`2021-03-12T15:02:28.572-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 2021/03/12 15:02:28 [DEBUG] PagerDuty - Preparing POST request to /response_plays with body: {"response_play":{"name":"Notify the Team","type":"response_play","description":"Notifies the Team for assistance using their main escalation policy","subscribers":[{"id":"Masked ID","type":"user_reference"}],"subscribers_message":"A notification has been sent out to the team for assistance.","responders":[{"type":"escalation_policy_reference","id":"Masked ID"}],"responders_message":"","runnability":"responders","from_email":"someone@example.com"}}
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 2021/03/12 15:02:28 [DEBUG] PagerDuty API Request Details:
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: ---[ REQUEST ]---------------------------------------
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: POST /response_plays HTTP/1.1
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Host: api.pagerduty.com
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: User-Agent: heimweh/go-pagerduty(terraform)
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Content-Length: 494
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Accept: application/vnd.pagerduty+json;version=2
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Authorization: Token token=hidingthetoken
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Content-Type: application/json
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: From: someone@example.com
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Accept-Encoding: gzip
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: {
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:  "response_play": {
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "name": "Notify the Team",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "type": "response_play",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "description": "Notifies the Team for assistance using their main escalation policy",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "subscribers": [
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:    {
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:     "id": "MaskedID",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:     "type": "user_reference"
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:    }
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   ],
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "subscribers_message": "A notification has been sent out to the team for assistance.",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "responders": [
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:    {
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:     "type": "escalation_policy_reference",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:     "id": "MaskedID"
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:    }
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   ],
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "responders_message": "",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "runnability": "responders",
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:   "from_email": "someone@example.com"
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5:  }
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: }
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 
2021-03-12T15:02:28.573-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: -----------------------------------------------------
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 2021/03/12 15:02:28 [DEBUG] PagerDuty API Response Details:
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: ---[ RESPONSE ]--------------------------------------
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: HTTP/2.0 500 Internal Server Error
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Content-Length: 0
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Date: Fri, 12 Mar 2021 20:02:29 GMT
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: Server: nginx
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: -----------------------------------------------------
2021-03-12T15:02:28.746-0500 [DEBUG] plugin.terraform-provider-pagerduty_v1.9.5: 2021/03/12 15:02:28 [TRACE] Waiting 10s before next try`

**Comment by stmcallister** [comment] 2021-03-15 19:24
@christopherbox It appears that the user making the API calls does not have permissions to edit Response Plays on the account. However, there is a bug that is causing the wrong error status to be returned by the API. The PagerDuty engineering team is now aware and creating a fix is on their radar.

@li-adrienloiseau We couldn't determine which account you are using. If you'd like to share that information either here or reach out to me directly at smcallister@pagerduty.com we can look further into you your specific issue.

**Comment by christopherbox** [comment] 2021-03-15 20:15
@stmcallister That user has an API Access key with the Access Level of "Full Access". What more do I need in order to enable permissions?

**Comment by stmcallister** [comment] 2021-03-16 22:47
@christopherbox are they able to edit response plays in question with the UI?

**Comment by christopherbox** [comment] 2021-03-22 19:26
The API key is generated by the "API Access Keys" page on the website. So in theory, the key is isolated from the user from my understanding.

However this isn't about editing. This is about creating a response play from scratch. The response play doesn't exist.

If a user with permissions wants to edit a response play in the UI, then they can.

**Comment by stmcallister** [comment] 2021-03-24 01:12
@christopherbox It appears there may be something wrong with your specific permissions. As mentioned, according to our logs the user making the API calls doesn't have permissions to edit or create response plays. I have the email address of the user, if you'd like to investigate more on your end. I'm not sure if you're comfortable with me posting that address here or if you'd rather reach out to me directly, you can reach me at smcallister@pagerduty.com.

**Comment by stmcallister** [comment] 2021-03-26 22:41
After @christopherbox took our conversation to email I realized I originally misunderstood the issue. It's not the owner of the API key who doesn't have the necessary permissions, it's actually the user associated with the email address given in the `from` field of the response play request. @li-adrienloiseau you'll want to make sure the email used in the `from` field is for a user with permissions to create and edit response plays.

**Comment by stmcallister** [comment] 2021-04-08 16:34
Going to close this issue. Please repost if you have any further questions.

**Closed by stmcallister** 2021-04-08 16:34 UTC
