### ISSUE TITLE
Unexpected diffs on pagerduty_extension after 1.2.0 release

### ISSUE THREAD

**Issue by tdmalone** [PagerDuty/terraform-provider-pagerduty#94] opened 2018-08-17 02:51 UTC
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.32.0
+ provider.dns v2.0.0
+ provider.null v1.0.0
+ provider.pagerduty v1.2.0
+ provider.statuscake v0.2.0
```

Same issue occurs after upgrading to Terraform v0.11.8.

### Affected Resource(s)
Please list the resources as a list, for example:
- [`pagerduty_extension`](https://www.terraform.io/docs/providers/pagerduty/r/extension.html)

### Terraform Configuration Files
```hcl
resource "pagerduty_extension" "slack" {
  name              = "Slack"
  endpoint_url      = ""
  extension_schema  = "${data.pagerduty_extension_schema.slack.id}"
  extension_objects = ["${pagerduty_service.main.id}"]
}

data "pagerduty_extension_schema" "slack" {
  name = "Slack"
}

resource "pagerduty_service" "main" {
  name = "Test"
  ...
}
```

### Expected Behavior
No diff should have occurred with our various Slack extensions, as nothing has changed in our configuration or in our setup within PagerDuty.

There has been a pagerduty provider update which made changes to `pagerduty_extension`, but it is a minor release and so is expected to be backwards-compatible.

### Actual Behavior
After upgrading to [v1.2.0](https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/CHANGELOG.md#120-august-16-2018), we started receiving these diffs, which are attempting to remove our existing Slack extension configurations:

```
  ~ module.pagerduty.module.high_priority.pagerduty_extension.slack
      config: "{\"bot\":{\"bot_user_id\":\"UXXXXXXXX\"},\"incoming_webhook\":{\"channel\":\"#ops-alerts\",\"channel_id\":\"CXXXXXXXX\",\"configuration_url\":\"https://astute.slack.com/services/BXXXXXXXX\",\"url\":\"https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/xxxxxxxxxxxxxxxx\"},\"notify_types\":{\"acknowledge\":true,\"assignments\":true,\"resolve\":true},\"ok\":true,\"restrict\":\"pd-users\",\"scope\":\"identify,bot,incoming-webhook,channels:read,groups:read,im:read,users:read,users:read.email,chat:write:bot,groups:write\",\"team_id\":\"TXXXXXXXX\",\"team_name\":\"Test\",\"user_id\":\"UXXXXXXXX\"}" => ""

  ~ module.pagerduty.module.low_priority.pagerduty_extension.slack
      config: "{\"bot\":{\"bot_user_id\":\"UXXXXXXXX\"},\"incoming_webhook\":{\"channel\":\"#ops-alerts\",\"channel_id\":\"CXXXXXXXX\",\"configuration_url\":\"https://astute.slack.com/services/BXXXXXXXX\",\"url\":\"https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/xxxxxxxxxxxxxxxx\"},\"notify_types\":{\"acknowledge\":true,\"assignments\":true,\"resolve\":true},\"ok\":true,\"restrict\":\"pd-users\",\"scope\":\"identify,bot,incoming-webhook,channels:read,groups:read,im:read,users:read,users:read.email,chat:write:bot,groups:write\",\"team_id\":\"TXXXXXXXX\",\"team_name\":\"Test\",\"user_id\":\"UXXXXXXXX\"}" => ""
```

I'm in a hurry so haven't got time to properly look into it, but I thought I will just log this for now and downgrade our version until I can come back at look at it properly.

**Comment by acrewdson** [comment] 2018-11-05 14:59
I'm seeing something that's probably related, so I'll just report it here and not open a new issue unless you think I should. I'm on Terraform `0.11.10` and `1.2.0` of the provider. I have a resource like:

```
resource "pagerduty_extension" "my_webhook" {
  name              = "my-webhook"
  endpoint_url      = "https://foo/bar"
  extension_schema  = "${data.pagerduty_extension_schema.webhook-v1.id}"
  extension_objects = ["${pagerduty_service.my_service.id}"]
}
```

And even though I haven't made changes, each time I `apply` I see:

```
  ~ pagerduty_extension.my_webhook
      config: "{}" => ""
```

Again, it sounds like this might be covered in @heimweh's PR mentioned above, and in that case, many thanks for that fix. If it seems unrelated, let me know and I will open a new issue. Thanks!

**Comment by pdecat** [comment] 2018-12-20 17:30
Hi @tdmalone,

> I'm not quite sure of the purpose of defining this config in Terraform.

The `config` field can be used to reuse an existing Slack OAuth token to setup additional service extensions.

Here's how we do it:

```
  extension_config_slack = {
    restrict = "any"

    ok = "true"

    notify_types {
      resolve     = "false"
      acknowledge = "false"
      assignments = "false"
      annotate    = "false"
    }

    scope = "identify,bot,incoming-webhook,channels:read,groups:read,im:read,users:read,users:read.email,chat:write:bot,groups:write"

    user_id   = "${var.pagerduty_slack_extension["user_id"]}"
    team_name = "${var.pagerduty_slack_extension["team_name"]}"
    team_id   = "${var.pagerduty_slack_extension["team_id"]}"

    incoming_webhook = {
      channel           = "${var.pagerduty_slack_extension["incoming_webhook_channel"]}"
      channel_id        = "${var.pagerduty_slack_extension["incoming_webhook_channel_id"]}"
      configuration_url = "${var.pagerduty_slack_extension["incoming_webhook_configuration_url"]}"
      url               = "${var.pagerduty_slack_extension["incoming_webhook_url"]}"
    }

    bot {
      bot_user_id = "${var.pagerduty_slack_extension["bot_user_id"]}"
    }

    access_token = "${var.pagerduty_slack_extension["access_token"]}"
  }

  # FIXME: replace() is needed because jsonencode() encodes booleans as strings until 0.12, cf. https://github.com/hashicorp/terraform/issues/17033

  extension_config_slack_json = "${replace(jsonencode(local.extension_config_slack), "/\"(true|false|[[:digit:]]+)\"/", "$1")}"
}

data "pagerduty_extension_schema" "slack" {
  name = "Slack"
}

resource "pagerduty_extension" "slack_nbh" {
  count = "${length(var.customers_nbh)}"

  name = "${pagerduty_team.team.name} - ${element(var.customers_nbh, count.index)} NBH - ${var.pagerduty_slack_extension["incoming_webhook_channel"]} in ${var.pagerduty_slack_extension["workspace_name"]}"

  endpoint_url = ""

  extension_schema  = "${data.pagerduty_extension_schema.slack.id}"
  extension_objects = ["${element(pagerduty_service.nbh.*.id, count.index)}"]

  config = "${local.extension_config_slack_json}"
}
```

To retrieve a token from a existing service extension:

```
# export PAGERDUTY_API_TOKEN=******
# export PAGERDUTY_SERVICE_ID=******
# export SLACK_WORKSPACE=*****.slack.com
# curl -s -X GET --header 'Accept: application/vnd.pagerduty+json;version=2' --header "Authorization: Token token=$PAGERDUTY_API_TOKEN" "https://api.pagerduty.com/extensions?extension_object_id=$PAGERDUTY_SERVICE_ID&extension_schema_id=$PAGERDUTY_EXTENSION_ID&query=${SLACK_WORKSPACE}" | jq '.extensions[0].config.access_token'
```

**Comment by tdmalone** [comment] 2018-12-20 19:58
@pdecat Ooh that is nice indeed. Thank you for the use case! I like the idea of using jsonencode too. I’ve been using HEREDOC syntax elsewhere to make JSON more readable :)

**Comment by shaunmills3808** [comment] 2019-05-24 16:39
Is this still an issue in provider.pagerduty v1.2.1?

Terraform v0.11.14
+ provider.aws v2.10.0
+ provider.pagerduty v1.2.1

I am still having terraform show that the config variable always needs to be modified even if there is no change.

**Desired Behavior:**
 no change

**Actual Result:**
```
  ~ pagerduty_extension.ACK-Q-H-TEST2-SYN
      config:                       "{}" => ""

```

**Comment by tdmalone** [comment] 2019-05-24 19:18
> Is this still an issue in provider.pagerduty v1.2.1?

Yep, looks like #95 hasn’t been merged yet.

**Comment by tdmalone** [comment] 2019-10-18 02:15
Hey @pdecat, I'm finally back here today trying to use your method to re-use existing configurations. Are you still using this method, and if so, is the `access_token` now missing for you as well in the API response from PagerDuty?

**Comment by pdecat** [comment] 2019-10-18 09:25
Hi @tdmalone, yes I'm still using this extensively. No issue with the `access_token` so far.
I can still retrieve it from the API with the [curl command I posted above](https://github.com/terraform-providers/terraform-provider-pagerduty/issues/94#issuecomment-449075707).

The only recent change I noticed is that there are new fields:
- `referer`: the URL to the referring service https://<account>.pagerduty.com/services/P******/integrations
- `urgency`: a map to control per which incidents are pushed depending on their urgency, defaults to `{ "high": true, "low": true }`

**Comment by pdecat** [comment] 2019-10-18 15:24
@tdmalone I've noticed there's a new `Slack V2` available from the UI and API: https://support.pagerduty.com/docs/slack-integration-guide

The old one which I'm still using is now documented at https://www.pagerduty.com/docs/guides/slack-v1-integration-guide/

Maybe your issues are caused by using the new one? I did not test it yet.

**Comment by pdecat** [comment] 2019-10-18 17:05
@tdmalone I just tested and it looks like extensions newly created via the UI no longer have their `access_token` field exposed, no matter the extension schemas used.

It does not bother me so far because I'm always reusing the same token for all extensions, in the same slack workspace.

I would be in trouble if I needed to integrate with other slack workspaces.

Maybe someone should reach to Pagerduty support to get to the bottom of it.

**Comment by stmcallister** [comment] 2019-10-18 23:47
@pdecat @tdmalone I posted this internally at PagerDuty and will post back what I find out.

**Comment by pdecat** [comment] 2019-10-21 10:03
@tdmalone here's a work-around to recover the `access_token` when it is missing from the API response:
- go to the Pagerduty Service's Integrations page https://<account>.pagerduty.com/services/<service_id>/integrations
- edit the Extension that's missing the `access_token` from the API response, e.g. uncheck `Urgency:`/`High`
- click Save
- re-query the API

**Comment by pdecat** [comment] 2020-02-07 11:41
Sadly, retrieving the access token from the REST API no longer works since yesterday, it is now returned as `access_token": "redacted"`.

I've opened a discussion at https://community.pagerduty.com/t/access-token-used-for-service-extension-no-longer-accessible-from-rest-api/6729

**Comment by mr337** [comment] 2020-03-18 23:50
Reached out to PagerDuty support asking to revert the `access_token": "redacted"` behavior as it breaks this provider. They can't at this time but will make note of it. PD support recommended making the change manually via Web UI which isn't idea.

**Comment by pdecat** [comment] 2020-03-19 09:54
For the time being, there's a work-around using the `bot_user_id` and `bot_access_token` fields as described in https://community.pagerduty.com/t/access-token-used-for-service-extension-no-longer-accessible-from-rest-api/6729/9

You may even set the old `access_token` field to `redacted` to remove the diff, see https://community.pagerduty.com/t/access-token-used-for-service-extension-no-longer-accessible-from-rest-api/6729/10

Works for us for now.

**Comment by taiidani** [comment] 2020-03-19 16:32
Although to surface the other findings per that discussion: changing the `bot_access_token` will turn the Slack-side behavior to look as if the user for the token you've provided is posting all of the messages. It also breaks interactivity -- the "Acknowledge", "Add Note", etc. buttons no longer work if you set `bot_access_token`.

But at least it does post the messages again!

**Comment by mr337** [comment] 2020-03-19 16:49
Thanks @pdecat and @taiidani!

I'll ask my team which way the want to go. Having the interactive buttons are super handy, but in the end want to keep notifications working :)

**Comment by pdecat** [comment] 2020-03-19 19:55
> Although to surface the other findings per that discussion: changing the `bot_access_token` will turn the Slack-side behavior to look as if the user for the token you've provided is posting all of the messages. It also breaks interactivity -- the "Acknowledge", "Add Note", etc. buttons no longer work if you set `bot_access_token`.

Slack interactivity still works for us, and posts are still posted by the Pagerduty bot. Not sure why though.

**Comment by taiidani** [comment] 2020-03-20 00:35
Wow, odd. Yeah I'm not sure why yours works and mine doesn't. Seems like something that would consistently work/break the same?

Are you still using Slack V1 extensions per your earlier comment? I've been applying mine against V2 extensions and seeing the bot-replacement behavior. Not sure if that would make a difference.

**Comment by pdecat** [comment] 2020-03-20 09:06
We were using Slack v1 before, then switched to v2 in November.

**Comment by joshk0** [comment] 2020-03-30 22:48
The community post linking here is now closed. In lieu of that, I have a question for the people who want to configure this on their own pagerduty instance.

*Are you actually interested in maintaining your extension configuration with the pagerduty_extension resource, or just set the extension_objects parameter every time you add a new service?*

The latter is my personal use case, I could give a hoot if I had to do a one time configuration of the extension via the pagerduty UI, _as long as I can add all of my services to it via the API_, because I am programmatically declaring all my Services in the same way and want the same extensions and configuration to apply to all of them.

My suspicion is that most people probably are in the same boat, so if Pagerduty offered an endpoint for just updating the `extension_objects` field without having to repost the config, that'd solve most people's problems.

Please emoji here and if there's enough support for this approach, I guess I'll open a new support ticket or community topic or something to get that thru.

**Comment by taiidani** [comment] 2020-03-31 00:17
At our company we have an "application" module that Terraforms the GitHub repository, Sentry project, and PagerDuty service. It then ties all those services together (Sentry sends events to PagerDuty, PagerDuty sends events to Datadog+Slack, etc).

Because of the way this is configured each GitHub repository that we spin up gets its own PagerDuty service and thus its own separate `pagerduty_extension` resource. Each extension only has a single extension_object in it.

**Comment by avivgold098** [comment] 2021-02-01 11:30
> Although to surface the other findings per that discussion: changing the `bot_access_token` will turn the Slack-side behavior to look as if the user for the token you've provided is posting all of the messages. It also breaks interactivity -- the "Acknowledge", "Add Note", etc. buttons no longer work if you set `bot_access_token`.
> 
> But at least it does post the messages again!

@taiidani Hey! 
I'm experiencing the same behavior as you describe, may you found a solution to the interactivity issue?

**Comment by taiidani** [comment] 2021-02-03 07:51
@avivgold098 Unfortunately not. My team's current solution is to ignore the entire block after the initial creation of the resource:

```tf
# WARNING: The "config" property has been ignored to circumvent drift caused by the PagerDuty provider (access_token => "redacted")
# If you change any configuration in here or rotate the access key you will need to explicitly "terraform taint" this resource.
resource pagerduty_extension slack {
  # ...

  lifecycle {
    ignore_changes = [config]
  }
```

It's more or less ignoring the problem, but it lets our automation successfully create the resource without drift occurring.

**Comment by pdecat** [comment] 2021-02-03 14:22
[The `redacted` work-around](https://github.com/PagerDuty/terraform-provider-pagerduty/issues/94#issuecomment-601088500) is still working great for us. 

I had to adapt the `config` field's JSON a bit due to recent changes on the Pagerduty API side though:

```
locals {
  extension_config_slack = {
    for team_name, team in var.teams : team_name => {
      access_token = "redacted"
      app_id       = team.pagerduty_slack_extension["app_id"]

      authed_user = {
        id = team.pagerduty_slack_extension["user_id"]
      }

      # Using the same values as above makes it work again
      # see https://community.pagerduty.com/forum/t/access-token-used-for-service-extension-no-longer-accessible-from-rest-api/1674
      bot = {
        bot_access_token = team.pagerduty_slack_extension["user_access_token"]
        bot_user_id      = team.pagerduty_slack_extension["user_id"]
      }

      bot_access_token_v2 = team.pagerduty_slack_extension["bot_access_token"]
      bot_user_id         = team.pagerduty_slack_extension["bot_user_id"]

      enterprise            = null
      enterprise_id         = null
      is_enterprise_install = false

      notify_types = {
        acknowledge = false
        annotate    = true
        assignments = false
        escalate    = true
        resolve     = false
        trigger     = true
      }

      ok = true

      scope = "app_mentions:read,channels:join,channels:manage,channels:read,chat:write,chat:write.public,commands,groups:read,groups:write,im:read,im:write,incoming-webhook,pins:write,team:read,users:read,workflow.steps:execute"

      team = {
        name = team.pagerduty_slack_extension["team_name"]
        id   = team.pagerduty_slack_extension["team_id"]
      }
      team_name = team.pagerduty_slack_extension["team_name"]
      team_id   = team.pagerduty_slack_extension["team_id"]

      token_type = "bot"

      urgency = {
        high = true
        low  = true
      }

      user_id = team.pagerduty_slack_extension["user_id"]
    }
  }
}

data "pagerduty_extension_schema" "slack" {
  name = "Slack V2"
}

resource "pagerduty_extension" "slack_nbh" {
  for_each = { for name, customer in var.customers : name => customer if customer.nbh != "no" }

  name = substr(format("%s - %s NBH - %s in %s",
    pagerduty_team.teams[each.value.team].name,
    each.key,
    each.value.nbh == "test" ? var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_channel"] : var.teams[each.value.team].pagerduty_slack_extension_nbh["incoming_webhook_channel"],
    var.teams[each.value.team].pagerduty_slack_extension_nbh["workspace_name"]
  ), 0, 100)

  extension_schema  = data.pagerduty_extension_schema.slack.id
  extension_objects = [pagerduty_service.nbh[each.key].id]

  config = jsonencode(
    merge(
      local.extension_config_slack[each.value.team],
      {
        "referer" = format("%s/integrations", replace(pagerduty_service.nbh[each.key].html_url, "service-directory", "services"))
        incoming_webhook = (each.value.nbh == "test" ?
          {
            channel           = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_channel"]
            channel_id        = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_channel_id"]
            configuration_url = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_configuration_url"]
            url               = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_url"]
          } :
          {
            channel           = var.teams[each.value.team].pagerduty_slack_extension_nbh["incoming_webhook_channel"]
            channel_id        = var.teams[each.value.team].pagerduty_slack_extension_nbh["incoming_webhook_channel_id"]
            configuration_url = var.teams[each.value.team].pagerduty_slack_extension_nbh["incoming_webhook_configuration_url"]
            url               = var.teams[each.value.team].pagerduty_slack_extension_nbh["incoming_webhook_url"]
        })
      },
    )
  )
}

resource "pagerduty_extension" "slack_bh" {
  for_each = { for name, customer in var.customers : name => customer if customer.bh != "no" }

  name = substr(format("%s - %s BH - %s in %s",
    pagerduty_team.teams[each.value.team].name,
    each.key,
    var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_channel"],
    var.teams[each.value.team].pagerduty_slack_extension["workspace_name"]
  ), 0, 100)

  extension_schema  = data.pagerduty_extension_schema.slack.id
  extension_objects = [pagerduty_service.bh[each.key].id]

  config = jsonencode(
    merge(
      local.extension_config_slack[each.value.team],
      {
        "referer" = format("%s/integrations", replace(pagerduty_service.bh[each.key].html_url, "service-directory", "services"))
        incoming_webhook = {
          channel           = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_channel"]
          channel_id        = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_channel_id"]
          configuration_url = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_configuration_url"]
          url               = var.teams[each.value.team].pagerduty_slack_extension["incoming_webhook_url"]
        }
      },
    )
  )
}
```

PS: posted that configuration fragment here as the [Pagerduty community thread](https://community.pagerduty.com/forum/t/access-token-used-for-service-extension-no-longer-accessible-from-rest-api/1674) is now locked.

**Comment by avivgold098** [comment] 2021-02-09 16:47
@pdecat 
Hey! Thx for your time. How did you find what `bot_access_token_v2` & `bot_access_token_v2` values should be?

**Comment by pdecat** [comment] 2021-02-09 16:50
> @pdecat
> Hey! Thx for your time. How did you find what `bot_access_token_v2` & `bot_access_token_v2` values should be?

You should see them in the terraform diff after having set up one Slack extension in the web UI. From there, you can reuse the values for other extension.

**Comment by avivgold098** [comment] 2021-02-09 18:04
@pdecat  thx! this works!

**Comment by bobzoller** [comment] 2021-04-22 02:11
I cannot get the terraform diff nor the Pagerduty API to show any access token values at all.  not `access_token`, not `bot_access_token`, nor `bot_access_token_v2` appear in the output, even after clicking through the Authorize flow on the website.  🤷

**Comment by stmcallister** [comment] 2021-10-08 04:17
Closing, as I believe #381 addressed this issue. Please reopen if not. Thanks!

**Closed by stmcallister** 2021-10-08 04:17 UTC
